services:
  - type: web
    name: mpesa-stk
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: GUNICORN_CMD_ARGS
        value: "--workers=2 --threads=2 --timeout=120" 